apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-awesome-app
  annotations:
    nginx-tls-terminator-sidecar: "true"
  labels:
    app: my-awesome-app
spec:
  selector:
    matchLabels:
      app: my-awesome-app
  template:
    metadata:
      labels:
        app: my-awesome-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
