apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Point to deployment to be patched with the TLS terminating sidecar
resources:
- deployment.yaml

configMapGenerator:
- name: tls-terminator-conf
  behavior: create
  literals:
  - PROXY_LISTEN_PORT=8443
  - PROXY_UPSTREAM_PORT=80

secretGenerator:
- name: tls-terminator-cert
  files:
  - cert/tls.crt
  - cert/tls.key
  type: kubernetes.io/tls

patchesStrategicMerge:
- volume.yaml
- sidecar.yaml
