apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-awesome-app
spec:
  template:
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      - name: tls-terminator-cert
        secret:
          secretName: tls-terminator-cert
