name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@master
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: eknert/nginx-tls-terminator
        tag_with_ref: true
        tags: latest
        push: ${{ startsWith(github.ref, 'refs/tags/') }}