name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@master
    - name: Set selected color
      run: echo "::set-env name=TAG::${GITHUB_REF:1}"
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: eknert/nginx-tls-terminator
        tags: ${{ env.TAG }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        TAG: ${{ github.ref }}